# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stockSystem_pb2 as stockSystem__pb2


class stockSystemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Lookup = channel.unary_unary(
                '/stockSystem/Lookup',
                request_serializer=stockSystem__pb2.stockName.SerializeToString,
                response_deserializer=stockSystem__pb2.PriceVolume.FromString,
                )
        self.Trade = channel.unary_unary(
                '/stockSystem/Trade',
                request_serializer=stockSystem__pb2.tradingRequest.SerializeToString,
                response_deserializer=stockSystem__pb2.statusIndicator.FromString,
                )
        self.Update = channel.unary_unary(
                '/stockSystem/Update',
                request_serializer=stockSystem__pb2.updateRequest.SerializeToString,
                response_deserializer=stockSystem__pb2.statusIndicator.FromString,
                )


class stockSystemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Lookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Trade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_stockSystemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=stockSystem__pb2.stockName.FromString,
                    response_serializer=stockSystem__pb2.PriceVolume.SerializeToString,
            ),
            'Trade': grpc.unary_unary_rpc_method_handler(
                    servicer.Trade,
                    request_deserializer=stockSystem__pb2.tradingRequest.FromString,
                    response_serializer=stockSystem__pb2.statusIndicator.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=stockSystem__pb2.updateRequest.FromString,
                    response_serializer=stockSystem__pb2.statusIndicator.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stockSystem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class stockSystem(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stockSystem/Lookup',
            stockSystem__pb2.stockName.SerializeToString,
            stockSystem__pb2.PriceVolume.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Trade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stockSystem/Trade',
            stockSystem__pb2.tradingRequest.SerializeToString,
            stockSystem__pb2.statusIndicator.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stockSystem/Update',
            stockSystem__pb2.updateRequest.SerializeToString,
            stockSystem__pb2.statusIndicator.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
